local harpoon = require("harpoon")

harpoon:setup({})

vim.keymap.set("n", "<leader>a", function()
	harpoon:list():add()
end)
vim.keymap.set("n", "<C-e>", function()
	harpoon.ui:toggle_quick_menu(harpoon:list())
end)

vim.keymap.set("n", "<C-j>", function()
	harpoon:list():select(1)
end)
vim.keymap.set("n", "<C-k>", function()
	harpoon:list():select(2)
end)
vim.keymap.set("n", "<C-l>", function()
	harpoon:list():select(3)
end)
vim.keymap.set("n", "<C-J>", function()
	harpoon:list():select(4)
end)
vim.keymap.set("n", "<C-K>", function()
	harpoon:list():select(5)
end)
vim.keymap.set("n", "<C-L>", function()
	harpoon:list():select(6)
end)
-- vim.keymap.set("n", "<C->", function() ui.nav_file(4) end)

vim.keymap.set("n", "<leader>gt", function()
	term.sendCommand(1, vim.api.nvim_get_current_line())
end)

vim.cmd("highlight! HarpoonInactive guibg=NONE guifg=#63698c")
vim.cmd("highlight! HarpoonActive guibg=NONE guifg=white")
vim.cmd("highlight! HarpoonNumberActive guibg=NONE guifg=#7aa2f7")
vim.cmd("highlight! HarpoonNumberInactive guibg=NONE guifg=#7aa2f7")
vim.cmd("highlight! TabLineFill guibg=NONE guifg=white")
